### ISSUE TITLE
Don't work.

### ISSUE THREAD

**Issue by eloimuns** [AOKP/platform_manifest#20]
When i do the repo sync in jelly bean get a error.

Asking me for username and get these error:
fatal: https://github.com/AOKP/android_bionic/info/refs not found: did you run git update-server-info on the server?

**Comment by championswimmer** [comment]
use repo sync -f

# 

catch me on http://championswimmer.tk

**Comment by eloimuns** [comment]
the same error. Ask username for https://github.com... :(

**Comment by ghost** [comment]
are you trying to sync the ssh. server.. if not check the version of git you have installed..

**Comment by championswimmer** [comment]
create an account on github anyways ;)

# should remove the whole problem altoether even if it tries SSH or HTTPS

catch me on http://championswimmer.tk

**Comment by eloimuns** [comment]
Droyd, thanks for your answer. I look that can i use plataform manifest from your github. Can i do this?

championswimmer i have an account. when i put error 
fatal: https://github.com/AOKP/android_bionic/info/refs not found: did you run git update-server-info on the server.

**Comment by championswimmer** [comment]
# the problem of bionic diretory has ben solved :)

catch me on http://championswimmer.tk

**Comment by ghost** [comment]
How did you solve the problem?

**Comment by championswimmer** [comment]
# https://github.com/KangXperiaProject/platform_manifest/commit/2733f417d6f0ba6e281f62a592f87ece5683ed7b

catch me on http://championswimmer.tk

**Comment by eloimuns** [comment]
Look this:
eloimuns@Ubuntu:~/aokp$ repo init -u https://github.com/AOKP/platform_manifest.git -b jb

Your Name  [Eloi Carracedo Muns]:  
Your Email [eloimuns@Ubuntu.(none)]: 

Your identity is: Eloi Carracedo Muns <eloimuns@Ubuntu.(none)>
is this correct [y/N]? y

repo initialized in /home/eloimuns
eloimuns@Ubuntu:~/aokp$ repo sync
Fetching projects:   4% (14/345)  Username for 'https://github.com':

**Comment by eloimuns** [comment]
and if i put the user and password, this error:
fatal: https://github.com/AOKP/android_bionic/info/refs not found: did you run git update-server-info on the server?

**Comment by eloimuns** [comment]
and, if i do repo init -u git@github.com:AOKP/platform_manifest.git -b jb

Permission denied (publickey).

**Comment by championswimmer** [comment]
you need to add your ssh key to github

# 

catch me on http://championswimmer.tk

**Comment by ghost** [comment]
if you look at the AOKP git hub they have removed the word android from most if not all there repos... The mr1 branch of the default manifest has been updated..however the jelly bean default manifest has not... When you try to sync your manifest is calling things that no longer exist.. that is the problem... not ssh or server it just cant find the stuff.. if your not using a samsung crespo or htc msm8960-common you can try using mine.. i have updated it the best i could and have just finished a sync...

**Comment by championswimmer** [comment]
dude i say again ..

# https://github.com/KangXperiaProject/platform_manifest/commit/2733f417d6f0ba6e281f62a592f87ece5683ed7b

catch me on http://championswimmer.tk

**Comment by ghost** [comment]
that manifest does NOT WORK there was alot more changed than just bionic.....
Anyway i spoke to whitehawkx last night and he fixed it.. all 17+ changes to the aokp gethub have been implimented in the jb manifest now..

**Comment by eloimuns** [comment]
Champions, dont work. Say the same error.

Droyd, now i'm trying to with your platform.manifest.

At the moment, works good.

THANKS all for help

**Comment by ghost** [comment]
Use AOKP its is fixed.

**Comment by eloimuns** [comment]
Droyd what is the problem if i use your repo? 
Only 100mb for finish

**Comment by ghost** [comment]
I'm messing with mine.. just use AOKP its fixed now...

**Comment by eloimuns** [comment]
okey.

THANKS

**Comment by eloimuns** [comment]
NOW Working. Thanks for help.

Close the issue :dart:
