### ISSUE TITLE
Marshmallow: CyanogenSetupWizard

### ISSUE THREAD

**Issue by ashdkv** [AOKP/platform_manifest#33]
After removing CyanogenSetupWizard QuckSetting and Home Button does not work

**Comment by STELIX** [comment]
Have u tried reverting/adding CMSetupWizard to your local_roomservice?

**Comment by ashdkv** [comment]
@STELIX , yes, it also depend from /external/google and need to be defined in vendor/aokp/configs/common.mk , than everything work nice. With gapps also work nice.
