### ISSUE TITLE
Sometimes freezing on wake

### ISSUE THREAD

**Issue by Dodgexander** [AOKP/platform_manifest#38]
[log.zip](https://github.com/AOKP/platform_manifest/files/1423879/log.zip)
Sometimes, 2-3 times a day my phone fails to wake properly and crashes. When it happens the phone only shows the power menu if I hold the power button. Nothing else works.

At the beginning of my log it shows a fatal crash which I guess is three cause.

Any pointers?

**Comment by STELIX** [comment]
Sorry, not the right place to report issues.
